### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by kosecki123** [chronologic/chronos-dapp#13]
Steps to reproduce

1) Open https://chronologic.github.io/chronos-dapp/
2) Select Debt smart contract (URL has changed to https://chronologic.github.io/debt/)
3) Refresh the page in browser

Result:
404

Expected: 
You are on Debt Smart Contact page

**Comment by adibas03** [comment]
That is actually a feature of github pages.
That is used as a way to avoid problems with DDOS.
Atleast, so it is said.

**Comment by mqklin** [comment]
@adibas03 I guess it's because github doesn't support SPA. I would suggest you to use Firebase instead

**Comment by adibas03** [comment]
Hey @mqklin 
Thanks for the suggestion, I would look into that.
