### ISSUE TITLE
Reloading Step-5 "Watch" view fails

### ISSUE THREAD

**Issue by josipbagaric** [chronologic/chronos-dapp#17]
Steps to reproduce:
1. Go through the whole creation wizard.
2. Once at the Step 5 (Watch page) view, try reloading the view (Cmd+R in my case).
3. The following loader loops endlessly: https://www.screencast.com/t/jpIqMWO4idPX and the contract doesn't reappear.

**Comment by adibas03** [comment]
Already fixed in #18 branch
